# Generated by Django 2.2 on 2020-08-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='post',
            name='Grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='english', max_length=200),
        ),
    ]
