# Generated by Django 3.0.1 on 2020-08-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200815_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
